In [3]:
import numpy as np
import cv2

There are two tyoes of images:-
1. Grey Scale Image(Pixel value:0,1)
2. Black & White Images(Pixel value:0,255)
3. Color Image(Three channel:- RGB)(Pixel value:0,255)

Image Resolution:-

Total number of pixel in the image.

Eg:- Full-HD= 1920*1080


In [4]:
#Reading an image

img=cv2.imread('download.jpg')
print(type(img))
print(img.shape)
print(img)
cv2.imshow('window',img)
cv2.waitKey(0)

<class 'numpy.ndarray'>
(125, 201, 3)
[[[26  3 35]
  [30  8 37]
  [35 13 41]
  ...
  [33  9 19]
  [36 14 19]
  [33 12 15]]

 [[23  1 29]
  [25  4 29]
  [30 11 32]
  ...
  [33  9 19]
  [36 14 19]
  [34 13 16]]

 [[21  3 20]
  [23  6 20]
  [25  8 21]
  ...
  [33 10 18]
  [36 14 19]
  [37 16 19]]

 ...

 [[ 4  4  4]
  [ 4  4  4]
  [ 4  4  4]
  ...
  [ 0  5  4]
  [ 0  5  4]
  [ 0  5  4]]

 [[ 4  4  4]
  [ 4  4  4]
  [ 4  4  4]
  ...
  [ 0  5  4]
  [ 0  5  4]
  [ 0  5  4]]

 [[ 6  4  4]
  [ 6  4  4]
  [ 6  4  4]
  ...
  [ 2  4  4]
  [ 2  4  4]
  [ 2  4  4]]]


-1

In [5]:
#Converting Grey-Scale to Black-white


img_grey=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

cv2.imshow('window',img_grey)
print(img_grey.shape)
cv2.waitKey(0)


(125, 201)


-1

In [7]:
#Playing with RGB channel

imgBlue=img[:,:,0]
imgGreen=img[:,:,1]
imgRed=img[:,:,2]

new_img=np.hstack((imgBlue,imgGreen,imgRed))

cv2.imshow('window',new_img)
cv2.waitKey(0)


-1

In [6]:
#Image Resizing

img1=cv2.imread('download.jpg')
print(type(img))
print(img.shape)

img_resize=cv2.resize(img1,(800,800))
print(img_resize.shape)

#half-size resize
cv2.imshow('window',img1)
cv2.waitKey(0)

<class 'numpy.ndarray'>
(125, 201, 3)
(800, 800, 3)


-1

In [8]:
#Flipping an image

#img_flip=cv2.flip(img,0)
img_flip=cv2.flip(img,-1)
cv2.imshow('window',img_flip)
cv2.waitKey(0)

-1

In [11]:
#Cropping an image
# we can do it by slicing 

img_crop=img[0:80,0:80]
cv2.imshow('window',img_crop)
cv2.waitKey(0)

-1

In [12]:
#Saving an image

img_crop=img[0:80,0:80]

cv2.imwrite('fruits.png',img_crop)


True